
package sistema1;

import com.sun.awt.AWTUtilities;
import java.awt.Image;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.Shape;
import java.awt.Toolkit;
import java.awt.geom.RoundRectangle2D;
import javax.swing.JOptionPane;


public class interfaz extends javax.swing.JFrame {
    int x,y;

    public interfaz() {
        this.setUndecorated(true);
        initComponents();
        jLabelamarillo.setVisible(false);
        this.setLocationRelativeTo(null);
        Shape forma= new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height,27,27);
        AWTUtilities.setWindowShape(this, forma);
    }
    
   
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/iconHos.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonIniciarsesion = new javax.swing.JButton();
        jLabelrojo = new javax.swing.JLabel();
        jLabelicono = new javax.swing.JLabel();
        jLabelusuario = new javax.swing.JLabel();
        jTextFieldUusario = new javax.swing.JTextField();
        jLabelpass = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jLabelamarillo = new javax.swing.JLabel();
        jLabelverde = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonIniciarsesion.setBackground(new java.awt.Color(0, 0, 204));
        jButtonIniciarsesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonIniciarsesion.setForeground(new java.awt.Color(255, 255, 255));
        jButtonIniciarsesion.setText("Iniciar Sesion");
        jButtonIniciarsesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarsesionActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIniciarsesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 300, -1, -1));

        jLabelrojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rojo.png"))); // NOI18N
        jLabelrojo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelrojoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelrojoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelrojoMouseExited(evt);
            }
        });
        getContentPane().add(jLabelrojo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabelicono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/iconMed.png"))); // NOI18N
        getContentPane().add(jLabelicono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, -1, 140));

        jLabelusuario.setBackground(new java.awt.Color(255, 255, 255));
        jLabelusuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelusuario.setForeground(new java.awt.Color(255, 255, 255));
        jLabelusuario.setText("Usuario:");
        getContentPane().add(jLabelusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jTextFieldUusario.setBackground(new java.awt.Color(87, 89, 88));
        jTextFieldUusario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextFieldUusario.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jTextFieldUusario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 170, -1));

        jLabelpass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabelpass.setForeground(new java.awt.Color(255, 255, 255));
        jLabelpass.setText("Password:");
        getContentPane().add(jLabelpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        jPasswordField1.setBackground(new java.awt.Color(87, 89, 88));
        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        jLabelamarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amarillo.png"))); // NOI18N
        jLabelamarillo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelamarilloMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelamarilloMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelamarilloMouseExited(evt);
            }
        });
        getContentPane().add(jLabelamarillo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 20, -1));

        jLabelverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde.png"))); // NOI18N
        jLabelverde.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelverdeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelverdeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelverdeMouseExited(evt);
            }
        });
        getContentPane().add(jLabelverde, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabelFondo.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo_azul.jpg"))); // NOI18N
        jLabelFondo.setPreferredSize(new java.awt.Dimension(100, 100));
        jLabelFondo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelFondoMousePressed(evt);
            }
        });
        jLabelFondo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelFondoMouseDragged(evt);
            }
        });
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelFondoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseClicked
   // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoMouseClicked

    private void jLabelFondoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMouseDragged
    Point p= MouseInfo.getPointerInfo().getLocation();
    this.setLocation(p.x-x,p.y-y);
    // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoMouseDragged

    private void jLabelFondoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFondoMousePressed
        x=evt.getX();
        y=evt.getY();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabelFondoMousePressed

    private void jLabelrojoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrojoMouseClicked
     this.dispose();   // TODO add your handling code here:
    }//GEN-LAST:event_jLabelrojoMouseClicked

    private void jLabelrojoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrojoMouseEntered
     jLabelrojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rojo_c.png")));  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelrojoMouseEntered

    private void jLabelrojoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelrojoMouseExited
    jLabelrojo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/rojo.png"))); // TODO add your handling code here:
    }//GEN-LAST:event_jLabelrojoMouseExited

    private void jLabelamarilloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelamarilloMouseClicked
     this.setExtendedState(interfaz.MAXIMIZED_BOTH);  // TODO add your handling code here:
    }//GEN-LAST:event_jLabelamarilloMouseClicked

    private void jLabelamarilloMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelamarilloMouseEntered
     jLabelamarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amarillo_c.png"))); // TODO add your handling code here:
     // TODO add your handling code here:
    }//GEN-LAST:event_jLabelamarilloMouseEntered

    private void jLabelamarilloMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelamarilloMouseExited
      jLabelamarillo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amarillo.png"))); // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabelamarilloMouseExited

    private void jLabelverdeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelverdeMouseClicked
     this.setExtendedState(ICONIFIED);   // TODO add your handling code here:
    }//GEN-LAST:event_jLabelverdeMouseClicked

    private void jLabelverdeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelverdeMouseEntered
    jLabelverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde_c.png"))); // TODO add your handling code here:
       // TODO add your handling code here:
    }//GEN-LAST:event_jLabelverdeMouseEntered

    private void jLabelverdeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelverdeMouseExited
    jLabelverde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/verde.png"))); // TODO add your handling code here:
             // TODO add your handling code here:
    }//GEN-LAST:event_jLabelverdeMouseExited

    private void jButtonIniciarsesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarsesionActionPerformed
        String user = jTextFieldUusario.getText();
        String pass = jPasswordField1.getText();
        if(user.equals("usuario") && pass.equals("123"))
        {   
            this.dispose();
            Inicio in =new Inicio();
            in.setVisible(true);
        }else
        {
            JOptionPane.showMessageDialog(null,"Usuario o contraseña incorrecto");
        }
        
    }//GEN-LAST:event_jButtonIniciarsesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIniciarsesion;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelamarillo;
    private javax.swing.JLabel jLabelicono;
    private javax.swing.JLabel jLabelpass;
    private javax.swing.JLabel jLabelrojo;
    private javax.swing.JLabel jLabelusuario;
    private javax.swing.JLabel jLabelverde;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextFieldUusario;
    // End of variables declaration//GEN-END:variables
}
